serve:
  api:
    port: ${AUTHO_PORT:-24000}
    tls:
      cert:
        path: /etc/certs/cert.pem
      key:
        path: /etc/certs/key.pem

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: ${AUTHO_AUTHGATE_PUBLIC_URL:-https://localhost:20000}/ui/login
        return_to_query_param: return_to
        when:
          - error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html

access_rules:
  repositories:
    - file://./conf/access-rules.yaml

authenticators:
  bearer_token:
    enabled: true
    config:
      check_session_url: ${AUTHO_AUTHE_URL:-https://localhost:23000}/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      token_from:
        header: Authorization
  cookie_session:
    enabled: true
    config:
      check_session_url: ${AUTHO_AUTHE_URL:-https://localhost:23000}/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session

authorizers:
  allow:
    enabled: true

mutators:
  noop:
    enabled: true
